---
title: "Auto Correlation Demo"
author: "Dr. J"
date: "2/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
# Auto Correlation- definition and demonstration  

```{r}
r = rnorm(200)
plot(r[1:199], r[2:200])
```

## Suppose data are generated by by an AR(1)
```{r}
# 2000 observations, error terms, mean = 0, std = 0.1
n=200
sd_r = 0.32
r = rnorm(n, sd = sd_r)
# check:
print(paste('sd of data: ', sd(r)))
y = vector('numeric',n)
y[1] = r[1]
for(i in 2:n) y[i] = 0.5*y[i-1] + r[i]
plot(y, type='l')     
grid()

plot(y[1:199],y[2:200])
print(paste(mean(r), mean(y)))
sd(y)

acf1 = acf(r, ylab='r',xlab='lag', plot=F )
acf1DF = data.frame(lag=acf1$lag, acf=acf1$acf)

plot.acf1 <- ggplot(data = acf1DF, aes( x = lag, y = acf)) +
    geom_col( width = 0.2) +
    geom_hline(yintercept = 0,linetype='solid')+
    scale_x_continuous(breaks = seq(0,max(acf1$lag),10)) +
    scale_y_continuous(name = element_blank(), 
                       limits = c(-0.2,1)) +
    ggtitle("ACF\nY") +
    theme_bw()

plot.acf1
    
    
acf2 = acf(y, ylab='y',xlab='lag', plot=F)
acf2DF = data.frame(lag=acf2$lag, acf=acf2$acf)

plot.acf2 <- ggplot(data = acf2DF, aes( x = lag, y = acf)) +
    geom_col( width = 0.3, color='red') +
    geom_hline(yintercept = 0,linetype='solid')+
    scale_x_continuous(breaks = seq(0,max(acf1$lag),10)) +
    scale_y_continuous(name = element_blank(), 
                       limits = c(-0.2,1)) +
    ggtitle("ACF\nY1") +
    theme_bw()

plot.acf2


```

```{r}
boxplot(r,y)
```


```{r}
# Suppose the actual data are
x = c(1,2,3,4,5,6)
# print mean and variance of the data
print(paste('mean of x = ', mean(x)))
print(paste('var of x = ', var(x)))
print(paste('var of mean: ', var(x)/(length(x)-1)))
```      

Now suppose we over-sample the actual data
```{r}

xx = c(1,1,2,2,3,3,4,4,5,5,6,6)


r1 = acf(xx, lag.max=1, plot=F)$acf[2] # acf[1] = lag 0
print(paste('first serial correlation coefficient: ',r1))


# and look at mean, variance

print(paste('mean of xx = ', mean(xx)))
print(paste('var of xx = ', var(xx)))
```
 Yikes!  variance is too small


What's going on?
We've generated an AR(1) process.  Ramsey, *Statistical Sleuth*
indicates the variance of y is actually var($\hat y$)/(1-$\alpha$)


```{r}

print(paste('var(r) = ', var(r)))
# var estimate from stat sleuth
print(paste('var(y), rough estimate: ', var(xx)*(1+r1)/(1-r1)))
print(paste('var(y) = ', var(y)))

# get the coefSum
coefSum = 1.0
k = 1
ARcoef = 0.5
while(1){
  coefSumSave = coefSum
  coefSum =coefSum+ARcoef^(2*k)
  k=k+1
  if (abs(coefSum-coefSumSave) < 1.e-6) break
}
print (coefSum)

print(paste('var(y)=', var(y),' expected=',coefSum*sd_r^2))
  
```
```{r}
xxSample = vector('numeric')
for (i in 1:1000)
  xxSample[i] = mean(sample(xx,6, replace=T))

hist(xxSample)
print(paste('mean estimate: ',mean(xxSample)))
print(paste('var of mean: ', var(xxSample)))
```

```{r}
x = c(2, 1.6, 0.7, 1.5, 2.3, 2.3, 2.3, 1.3, 1.8, 1.0)
r =  c(-0.11,  0.11, -0.17, -0.09,  0.11, -0.10, -0.06,  0.04, -0.05,  0.07)

y = 2*x + 5 + r
model1 = lm(y~x)
summary(model1)

# but if the independence is violated..
x1 = 0.9*x + 0.15*r
model2 = lm(y~x1)
summary(model2)

cor(x,x1)
```

